import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>App de Películas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>
          Movie APP con Next.js
        </h1>
        <p>Bienvenido a la aplicación de películas</p>
        <nav>
          <Link  href="/movies">
            Ver películas
          </Link>
          <Link  href="/about">
            Acerca de
          </Link>
        </nav>
      </div>
    </>
  );
}
